### ISSUE TITLE
bug: Cannot find module '@rabbitholegg/questdk' or its corresponding type declarations.

### ISSUE THREAD

**Issue by carlomigueldy** [rabbitholegg/questdk-plugins#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-alpha.55

### Current Behavior

I am using pnpm package manager, I installed dependencies at the root directory however, on my plugin directory, it cannot read the library yet it exists in node_modules

![image](https://github.com/user-attachments/assets/738bb450-2b69-465d-bb9e-241ff405e3d4)

### Expected Behavior

It should detect the package installed in the monorepo after installing dependencies

### Steps To Reproduce

1. Clone repo
2. Install dependencies at root dir of repo
3. Check any existing plugins under packages directory, inspect the @rabbitholegg/questdk imports, it should highlight as an error with message "Cannot find module '@rabbitholegg/questdk' or its corresponding type declarations."

### Anything else?

I need assistance, I am building our own plugin for our platform https://limitless.exchange/

**Comment by mmackz** [comment]
Try `pnpm build --filter=@rabbitholegg/questdk`

**Comment by mmackz** [comment]
@carlomigueldy You still having issues?
